openapi: 3.0.2
info:
  title: Sample API Spec - v2
  description: |-
    This is a OpenAPI Yaml Spec designed to replicate an issue with scalar.  

    It comes from a project is to validate an "API Design First" approach
    for the public API, which should allow us to gather developer feedback
    prior to implementation in order to develop API endpoints more quickly.

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "2.0.0"

servers:
  - url: http://localhost:3000/v2
    description: Mock v2 Sample API Server

tags:
  - name: me
    description: Access details about the current user
  - name: categories
    description: Access to categories

components:
  schemas:
    userObject:
      properties:
        user_name:
          type: string
          description: User's name
        user_email:
          type: string
          description: User's email
        user_id:
          type: integer
          format: int64
          description: Unique identifier for user
        account_id:
          type: integer
          format: int64
          description: Unique identifier for the associated budgeting account
      required:
        - user_name
        - user_email
        - user_id
        - account_id
      type: object
      additionalProperties: true

    # The categoryObject is used to represent a category that is not a
    # category group. Therefore the is_group attribute is always false
    categoryObject:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
          nullable: false
          description: A system defined unique identifier for the category.
        name:
          type: string
          nullable: false
          description: The name of the category.
          minLength: 1
          maxLength: 100
        description:
          type: string
          nullable: true
          description: The description of the category or `null` if not set.
          maxLength: 200
        is_income:
          type: boolean
          nullable: false
          description: If true, the transactions in this category will be treated as income.
        exclude_from_budget:
          type: boolean
          nullable: false
          description: If true, the transactions in this category will be excluded from the budget.
        exclude_from_totals:
          type: boolean
          nullable: false
          description: If true, the transactions in this category will be excluded from totals.
        updated_at:
          type: string
          format: date-time
          nullable: false
          description: The date and time of when the category was last updated (in the ISO 8601 extended format).
        created_at:
          type: string
          format: date-time
          nullable: false
          description: The date and time of when the category was created (in the ISO 8601 extended format).
        is_group:
          type: boolean
          enum: [false]
          description: For categoryObject, is_group is always false.
        group_id:
          type: integer
          format: int64
          nullable: true
          description: The ID of the category group this category belongs to
            or `null` if the category doesn't belong to a group, or is itself
            a category group.
        archived:
          type: boolean
          nullable: true
        archived_on:
          type: string
          format: date-time
          nullable: true
          description: The date and time of when the category was last archived (in the ISO 8601 extended format).
        order:
          type: number
          nullable: false
        # This attribute is only seen in the categoryObject and should not
        # be copied to the categoryGroup Object
        group_name:
          type: string
          description: For grouped categories, the name of the category group.
            If `is_group `is false, this attribute will not exist. If it is
            true, this attribute will contain the name of the category with
            the id specified in `group_id`
      required:
        - id
        - name
        - description
        - is_income
        - exclude_from_budget
        - exclude_from_totals
        - is_group
        - group_id
        - archived
        - archived_on
        - order

    # The categorGroupObject is used to represent a category that is not a
    # category group. Therefore the is_group attribute is always true
    # Since the use of the allOf attribute in OpenAPI causes issues with
    # doc generation and validation, this schema is mostly cut and paste
    # from the categoryObject.
    # Future editors of this document should not directly change any of the
    # non group properties in this schema here, but should change them as
    # needed in the categoryObject and then copy them into this object
    categoryGroupObject:
      type: object
      properties:
        # Beginning of cut and paste section from categoryObject
        id:
          type: integer
          format: int64
          nullable: false
          description: A system defined unique identifier for the category.
        name:
          type: string
          nullable: false
          description: The name of the category.
          minLength: 1
          maxLength: 100
        description:
          type: string
          nullable: true
          description: The description of the category or `null` if not set.
          maxLength: 200
        is_income:
          type: boolean
          nullable: false
          description: If true, the transactions in this category will be treated as income.
        exclude_from_budget:
          type: boolean
          nullable: false
          description: If true, the transactions in this category will be excluded from the budget.
        exclude_from_totals:
          type: boolean
          nullable: false
          description: If true, the transactions in this category will be excluded from totals.
        updated_at:
          type: string
          format: date-time
          nullable: false
          description: The date and time of when the category was last updated (in the ISO 8601 extended format).
        created_at:
          type: string
          format: date-time
          nullable: false
          description: The date and time of when the category was created (in the ISO 8601 extended format).
        # This property is in both the category and categoryGroup object but
        # the value is always false for a category and true for a categoryGroup
        is_group:
          type: boolean
          enum: [true]
          description: For categoryGroupObject, is_group is always true.
        group_id:
          type: integer
          format: int64
          nullable: true
          description: The ID of the category group this category belongs to
            or `null` if the category doesn't belong to a group, or is itself
            a category group.
        archived:
          type: boolean
          nullable: true
        archived_on:
          type: string
          format: date-time
          nullable: true
          description: The date and time of when the category was last archived (in the ISO 8601 extended format).
        order:
          type: number
          nullable: false
        # These properites are unique to the categoryGroupObject
        children:
          type: array
          items:
            type: integer
          description: For category groups, this will populate with the child category IDs.
        hydrated_children:
          type: array
          items:
            $ref: "#/components/schemas/categoryObject"
          description: For category groups, and when requested via the
            `hydrate_children` query parameter this attribute will include the
            full category object for each of the child categories that belong
            to this category group.
          nullable: true
      required:
        - id
        - name
        - description
        - is_income
        - exclude_from_budget
        - exclude_from_totals
        - is_group
        - group_id
        - archived
        - archived_on
        - order
        - children
    errorResponseObject:
      type: object
      properties:
        message:
          type: string
          description: overall error message
        errors:
          type: array
          items:
            # This is currently an open ended object but we may want to standardize
            # We may wish to enumerate error codes
            type: object
      required:
        - message
        - errors


  responses:
    # errors
    unauthorizedToken:
      description: Unauthorized.  This error occurs when an invalid API token is passed to the request.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponseObject"
          example:
            message: Unauthorized
            errors:
              - errMsg: Access token does not exist.
    rateLimited:
      description: Too Many Requests. Retry your request after the number of seconds specified in the retry-after header.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponseObject"
          example:
            message: Too Many Requests
            errors:
              - errMsg: Too many requests, please try again later.
    serverError:
      description: Internal Server Error. Contact support.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponseObject"
          example:
            message: Internal Server Error
            errors:
              - errMsg: Currently in maintenance mode. Please try again in a few minutes.

  securitySchemes:
    bearerSecurity:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth:
      type: apiKey
      in: cookie
      name: _lm_access_token

paths:
  /me:
    get:
      tags:
        - me
      description: >-
        Get details about the user associated with the supplied
        authorization token.
      operationId: getMe
      parameters: []
      responses:
        "200":
          description: The User Object associated with the authorized token.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userObject"
              example:
                user_name: User 1
                user_email: user-1@sample.dev
                user_id: 18328
                account_id: 18221
        "401":
          $ref: "#/components/responses/unauthorizedToken"
        "429":
          $ref: "#/components/responses/rateLimited"
        "5XX":
          $ref: "#/components/responses/serverError"
  /categories:
    get:
      tags:
        - categories
      summary: Get all categories
      description: Retrieve a list of all categories associated with the user's account.
      operationId: getAllCategories
      parameters:
        - name: format
          in: query
          description: If `flattened`, returns a singular array of categories,
            ordered alphabetically. If `nested`, returns top-level categories
            (either category groups or categories not part of a category group)
            in an array. Subcategories are nested within the category group
            under the property `children`.
          required: false
          schema:
            type: string
            default: flattened
            enum:
              - flattened
              - nested
        - name: ids
          in: query
          description: A form serialized array of category IDs to filter the
            results. If specified, the `format` and `hydrate_children`
            parameters are ignored and
            results are always `flattened`. IDs that do not exist are ignored.
          required: false
          schema:
            type: array
            items:
              type: integer
          style: form
          examples:
            children:
              value:
                - 315162
                - 315163
                - 315164
            top level:
              value:
                - 83
                - 84
        - name: hydrate_children
          in: query
          description: Set to true to have the list of `hydrated_children`
            objects returned as part of response for a category group.  This
            parameter is ignored if `flattened` is `true` since the full child
            category objects are returned in the list.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: A list of Category Objects
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      oneOf:
                        - $ref: "#/components/schemas/categoryObject"
                        - $ref: "#/components/schemas/categoryGroupObject"
              examples:
                flattened response:
                  value:
                    categories:
                      - id: 83
                        name: "Test Category"
                        description: "Test description"
                        is_income: false
                        exclude_from_budget: true
                        exclude_from_totals: false
                        updated_at: "2024-02-28T09:49:03.225Z"
                        created_at: "2024-01-28T09:49:03.225Z"
                        is_group: true
                        order: 0
                        archived: false
                        group_id: null
                        archived_on: null
                      - id: 84
                        name: "Test Category Group"
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: "2024-02-28T09:49:03.238Z"
                        created_at: "2024-01-28T09:49:03.238Z"
                        is_group: false
                        order: 1
                        archived: false
                        group_id: null
                        archived_on: null
                        children: [315162, 315163, 315164]
                      - id: 315162
                        name: "Alcohol, Bars"
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: "2024-02-28T09:49:03.238Z"
                        created_at: "2024-03-06T20:11:36.066Z"
                        is_group: false
                        order: 2
                        archived: false
                        group_id: 84
                        group_name: "Test Category Group"
                        archived_on: null
                      - id: 315163
                        name: "Groceries"
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: "2024-02-28T09:49:03.238Z"
                        created_at: "2024-03-06T20:11:36.120Z"
                        is_group: false
                        order: 3
                        archived: false
                        group_id: 84
                        group_name: "Test Category Group"
                        archived_on: null
                      - id: 315164
                        name: "Restaurants"
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: "2024-02-28T09:49:03.238Z"
                        created_at: "2024-03-06T20:11:36.146Z"
                        is_group: false
                        order: 4
                        archived: false
                        group_id: 84
                        group_name: "Test Category Group"
                        archived_on: null
                      - id: 315165
                        name: "Fast Food"
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: "2024-02-28T09:49:03.238Z"
                        created_at: "2024-03-06T20:11:36.146Z"
                        is_group: false
                        order: 4
                        archived: true
                        group_id: 84
                        group_name: "Test Category Group"
                        archived_on: "2024-02-28T09:49:03.238Z"
                nested response:
                  value:
                    categories:
                      - id: 83
                        name: Test Category
                        description: Test description
                        is_income: false
                        exclude_from_budget: true
                        exclude_from_totals: false
                        updated_at: 2020-01-28T09:49:03.225Z
                        created_at: 2020-01-28T09:49:03.225Z
                        is_group: true
                        order: 0
                        archived: false
                        group_id: null
                        archived_on: null
                      - id: 84
                        name: Test Category Group
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: 2020-01-28T09:49:03.238Z
                        created_at: 2020-01-28T09:49:03.238Z
                        is_group: false
                        order: 1
                        archived: false
                        group_id: null
                        archived_on: null
                        children: [315162, 315163, 315164]
                nested hydrated response:
                  value:
                    categories:
                      - id: 83
                        name: Test Category
                        description: Test description
                        is_income: false
                        exclude_from_budget: true
                        exclude_from_totals: false
                        updated_at: 2020-01-28T09:49:03.225Z
                        created_at: 2020-01-28T09:49:03.225Z
                        is_group: true
                        order: 0
                        archived: false
                        group_id: null
                        archived_on: null
                      - id: 84
                        name: Test Category Group
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: 2020-01-28T09:49:03.238Z
                        created_at: 2020-01-28T09:49:03.238Z
                        is_group: false
                        order: 1
                        archived: false
                        group_id: null
                        archived_on: null
                        children: [315162, 315163, 315164]
                        hydrated_children:
                          - id: 315162
                            name: "Alcohol, Bars"
                            description: null
                            is_income: true
                            exclude_from_budget: false
                            exclude_from_totals: true
                            updated_at: "2020-01-28T09:49:03.238Z"
                            created_at: "2022-03-06T20:11:36.066Z"
                            is_group: false
                            order: 2
                            archived: false
                            group_id: 84
                            archived_on: null
                          - id: 315162
                            name: "Groceries"
                            description: null
                            is_income: true
                            exclude_from_budget: false
                            exclude_from_totals: true
                            updated_at: "2020-01-28T09:49:03.238Z"
                            created_at: "2022-03-06T20:11:36.120Z"
                            is_group: false
                            order: 3
                            archived: false
                            group_id: 84
                            archived_on: null
                          - id: 315162
                            name: "Restaurants"
                            description: null
                            is_income: true
                            exclude_from_budget: false
                            exclude_from_totals: true
                            updated_at: "2020-01-28T09:49:03.238Z"
                            created_at: "2022-03-06T20:11:36.146Z"
                            is_group: false
                            order: 4
                            archived: false
                            group_id: 84
                            archived_on: null
                filtered response:
                  value:
                    categories:
                      - id: 315162
                        name: "Alcohol, Bars"
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: "2020-01-28T09:49:03.238Z"
                        created_at: "2022-03-06T20:11:36.066Z"
                        is_group: false
                        order: 2
                        archived: false
                        group_id: null
                        archived_on: null
                      - id: 315162
                        name: "Groceries"
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: "2020-01-28T09:49:03.238Z"
                        created_at: "2022-03-06T20:11:36.120Z"
                        is_group: false
                        order: 3
                        archived: false
                        group_id: null
                        archived_on: null
                      - id: 315162
                        name: "Restaurants"
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: "2020-01-28T09:49:03.238Z"
                        created_at: "2022-03-06T20:11:36.146Z"
                        is_group: false
                        order: 4
                        archived: false
                        group_id: null
                        archived_on: null
        "400":
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponseObject"
              example:
                message: "Request Validation Failure"
                errors:
                  - errMsg: "must be equal to one of the allowed values"
                    instancePath: "/query/format"
                    schemaPath: "#/properties/query/properties/format/enum"
                    keyword: "enum"
                    params:
                      allowedValues:
                        - "flattened"
                        - "nested"
        "401":
          $ref: "#/components/responses/unauthorizedToken"
        "429":
          $ref: "#/components/responses/rateLimited"
        "5XX":
          $ref: "#/components/responses/serverError"
  /categories/{id}:
    get:
      tags:
        - categories
      summary: Get a single category
      description: Retrieve details of a specific category or category group
        by its ID.
      operationId: getCategoryById
      parameters:
        - name: id
          in: path
          description: ID of the category to retrieve
          required: true
          schema:
            type: integer
          examples:
            category:
              summary: Example of a category's id
              value: 83
            category group:
              summary: Example of a category group's id
              value: 84
            id not found:
              summary: Example of an id that doesn't exist
              value: 543210
        - name: hydrate_children
          in: query
          description: Set to true to have the list of `hydrated_children`
            objects returned as part of response for a category group.
          required: false
          schema:
            type: boolean
            default: false

      responses:
        "200":
          description: Category Object with the requested category or category group.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/categoryObject"
                  - $ref: "#/components/schemas/categoryGroupObject"
              examples:
                category:
                  value:
                    id: 83
                    name: Test Category
                    description: Test description
                    is_income: false
                    exclude_from_budget: true
                    exclude_from_totals: false
                    updated_at: 2020-01-28T09:49:03.225Z
                    created_at: 2020-01-28T09:49:03.225Z
                    is_group: true
                    order: 0
                    archived: false
                    group_id: null
                    archived_on: null
                category group:
                  value:
                    id: 84
                    name: Test Category Group
                    description: null
                    is_income: true
                    exclude_from_budget: false
                    exclude_from_totals: true
                    updated_at: "2020-01-28T09:49:03.238Z"
                    created_at: "2020-01-28T09:49:03.238Z"
                    is_group: false
                    group_id: null
                    order: 1
                    archived: false
                    archived_on: null
                    children:
                      - 315162
                      - 315163
                      - 315164
                hydrated category group:
                  value:
                    id: 84
                    name: Test Category Group
                    description: null
                    is_income: true
                    exclude_from_budget: false
                    exclude_from_totals: true
                    updated_at: "2020-01-28T09:49:03.238Z"
                    created_at: "2020-01-28T09:49:03.238Z"
                    is_group: false
                    group_id: null
                    order: 1
                    archived: false
                    archived_on: null
                    children:
                      - 315162
                      - 315163
                      - 315164
                    hydrated_children:
                      - id: 315162
                        name: "Alcohol, Bars"
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: "2020-01-28T09:49:03.238Z"
                        created_at: "2022-03-06T20:11:36.066Z"
                        is_group: false
                        order: 2
                        archived: false
                        group_id: 84
                        archived_on: null
                      - id: 315163
                        name: "Groceries"
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: "2020-01-28T09:49:03.238Z"
                        created_at: "2022-03-06T20:11:36.120Z"
                        is_group: false
                        order: 3
                        archived: false
                        group_id: 84
                        archived_on: null
                      - id: 315164
                        name: "Restaurants"
                        description: null
                        is_income: true
                        exclude_from_budget: false
                        exclude_from_totals: true
                        updated_at: "2020-01-28T09:49:03.238Z"
                        created_at: "2022-03-06T20:11:36.146Z"
                        is_group: false
                        order: 4
                        archived: false
                        group_id: 84
                        archived_on: null
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponseObject"
              example:
                message: "Request Validation Failure"
                errors:
                  - errMsg: "must be boolean"
                    instancePath: "/query/hydrate_children"
                    schemaPath: "#/properties/query/properties/hydrate_children/type"
                    keyword: "type"
                    params:
                      type: "boolean"
        "401":
          $ref: "#/components/responses/unauthorizedToken"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponseObject"
              example:
                message: Not Found
                errors:
                  - errMsg: There is no category with the id:'543210'`
        "429":
          $ref: "#/components/responses/rateLimited"
        "5XX":
          $ref: "#/components/responses/serverError"

security:
  - bearerSecurity: []
  - cookieAuth: []